    name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3' # Update to your desired Xcode version

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Build app
        run: |
          xcodebuild clean build \
            -workspace LeetCode.xcworkspace \
            -scheme LeetCode \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'

      - name: Run tests
        run: |
          xcodebuild test \
            -workspace LeetCode.xcworkspace \
            -scheme LeetCode \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'
